name: Terraform

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-infra
  cancel-in-progress: false

jobs:

  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure Plan Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::627807502978:role/skilli-prod-github-infra-plan-role
          aws-region: ap-south-1

      - uses: hashicorp/setup-terraform@v3

      - run: terraform fmt -check -recursive

      - run: terraform init -input=false

      - run: terraform validate

      - run: terraform plan -input=false -lock=false -var-file=prod.tfvars

  terraform-apply:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    needs:
      - terraform-plan

    steps:
      - uses: actions/checkout@v4

      - name: Configure Deploy Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::627807502978:role/skilli-prod-github-infra-role
          aws-region: ap-south-1

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init -input=false

      - run: terraform apply -input=false -auto-approve -var-file=prod.tfvars
